default:
  path:     /
  defaults: { _controller:AppBundle:Article:getPublicArticles }
articles_admin:
  path:     /admin/articles/
  defaults: { _controller:AppBundle:Article:getAllArticles }
articles_public:
  path:     /articles/
  defaults: { _controller:AppBundle:Article:getPublicArticles }
article_one:
  path:     /article/{menu}/{id}_{slug}.html
  defaults: { _controller:AppBundle:Article:getArticle }
  requirements:
    id: \d+
articles_new:
  path:     /admin/articles/new/
  defaults: { _controller:AppBundle:Article:newArticle }
articles_update:
  path:     /admin/articles/update/{id}
  defaults: { _controller:AppBundle:Article:newArticle }
  requirements:
      id: \d+
articles_remove:
  path:     /admin/articles/remove/{id}
  defaults: { _controller:AppBundle:Article:deleteArticle }
  requirements:
      id: \d+